server:
  port: 8000
spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*" # 允许哪些网站的跨域请求
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
      routes:
        - id: route-cinema
          uri: lb://cinema
          predicates:
            - Path=/cinema/**
        - id: route-film
          uri:  lb://film
          predicates:
            - Path=/film/**
        - id: route-user
          uri: lb://user
          predicates:
            - Path=/user/**
        - id: route-order
          uri: lb://user
          predicates:
            - Path=/order/**
    nacos:
      discovery:
        server-addr: localhost:8848
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
        namespace: public
  application:
    name: gateway