server:
  port: 8001
spring:
  application:
    name: cinema
  datasource:
    url: jdbc:mysql://localhost:3306/film_buy?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver